### ISSUE TITLE
Doxygen automático com padrões errados

### ISSUE THREAD

**Issue by Eduardo-Barreto** [Team-Micras/MicrasFirmware#1]
Alguma extensão (provavelmente alguma [como essa](https://marketplace.visualstudio.com/items?itemName=cschlosser.doxdocgen)) ta criando os doxygen de arquivos com o padrão de outro repositório.

Isso pode ser visto em quase qualquer arquivo criado pelo santi, vou deixar um exemplo aleatório aqui.

Provavelmente é facilmente resolvível mexendo nos arquivos do .vscode, mas sem saber exatamente qual extensão ta sendo usada é difícil dizer exatamente qual e como

https://github.com/Team-Micras/MicrasFirmware/blob/7862ea6b29d880342b577867957ed4d8058080e6/inc/proxy/button.hpp#L4

**Comment by PedroDeSanti** [comment]
Obrigado pela observação, já foi resolvido
